name: Concurrency Test - Job
on:
  workflow_dispatch:

jobs:

  job1:
    name: First job that acquires the lock
    runs-on: ubuntu-latest
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: sleep 10
  
  wait2:
    name: Pause before the second job starts
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5

  job2:
    name: Second job sensitive to the lock for execution or cancellation
    runs-on: ubuntu-latest
    needs: wait2
    concurrency:
      group: lock-job
      cancel-in-progress: false
    strategy:
      matrix:
        iterator: [ 1, 2, 3, 4, 5 ]
    steps:
      - run: echo "Any previously pending job or workflow in the concurrency group will be canceled."

  wait3:
    name: Pause before the third job starts
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5

  job3:
    name: Third job sensitive to the lock for execution or cancellation
    runs-on: ubuntu-latest
    needs: wait3
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: echo "Any previously pending job or workflow in the concurrency group will be canceled."
