name: Concurrency Test - Job
on:
  workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: false

jobs:
#   wait:
#     name: Wait
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "Wait"
#           sleep 5

  job1:
    runs-on: ubuntu-latest
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: sleep 5

  job2:
    runs-on: ubuntu-latest
    needs: job1
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: sleep 5
