name: Concurrency Test - Job
on:
  workflow_dispatch:

jobs:
  wait1:
    name: Wait 1s
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1

  # wait5:
  #   name: Wait 5s
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: sleep 5

  job1:
    name: First job that acquires the lock
    runs-on: ubuntu-latest
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: sleep 10

  job2:
    name: Second job sensitive to the lock for execution or cancellation
    runs-on: ubuntu-latest
    # needs: wait5
    needs: wait1
    concurrency:
      group: lock-job
      cancel-in-progress: false
    strategy:
      matrix:
        iterator: [ 1, 2, 3 ]
    steps:
      - run: echo "Any previously pending job or workflow in the concurrency group will be canceled."

  job3:
    name: Third job sensitive to the lock for execution or cancellation
    runs-on: ubuntu-latest
    needs: wait1
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: echo "Any previously pending job or workflow in the concurrency group will be canceled."
