name: Concurrency Test - Job
on:
  workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: false

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5

  job1:
    runs-on: ubuntu-latest
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: sleep 10

  job2:
    strategy:
      matrix:
        version: [ 1, 2, 3, 4, 5 ]
    runs-on: ubuntu-latest
    needs: wait
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: sleep 5

  job3:
    runs-on: ubuntu-latest
    needs: wait
    concurrency:
      group: lock-job
      cancel-in-progress: false
    steps:
      - run: sleep 5
