name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

concurrency:
  group: lock-${{ inputs.username }}
  cancel-in-progress: true

jobs:
  reusable-job:
    name: Job - ${{ inputs.username }}
    runs-on: ubuntu-latest
    concurrency:
      group: lock-global
      cancel-in-progress: false
    steps:
      - name: Hello! ${{ inputs.username }}
        run: | 
          echo Hello! ${{ inputs.username }}
          sleep 10

  # reusable-job1:
  #   name: Job 1 - ${{ inputs.username }}
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: lock-global1
  #     cancel-in-progress: false
  #   strategy:
  #     matrix:
  #       intro: ["Hi,", "¡Hola!"]
  #   steps:
  #     - name: ${{ matrix.intro }} ${{ inputs.username }}
  #       run: | 
  #         echo ${{ matrix.intro }} ${{ inputs.username }}
  #         sleep 5
