name: Concurrency in Reusable Workflows

on:
  workflow_dispatch:

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "initialize"
          sleep 3

  concurrency-test1:
    uses: lucetre/action-concurrency/.github/workflows/reusable-workflow.yaml@main
    with:
      username: lucetre

  concurrency-test2:
    needs: initialize
    uses: lucetre/action-concurrency/.github/workflows/reusable-workflow.yaml@main
    with:
      username: aslan
