name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

concurrency:
  group: lock-${{ inputs.username }}
  cancel-in-progress: true

jobs:
  # reusable-job1:
  #   name: Job 1 - ${{ inputs.username }}
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: lock-global1
  #     cancel-in-progress: false
  #   strategy:
  #     matrix:
  #       intro: ["Hi,", "¡Hola!"]
  #   steps:
  #     - name: ${{ matrix.intro }} ${{ inputs.username }}
  #       run: | 
  #         echo ${{ matrix.intro }} ${{ inputs.username }}
  #         sleep 5

  reusable-job2:
    name: Job 2 - ${{ inputs.username }}
    runs-on: ubuntu-latest
    concurrency:
      group: lock-global2
      cancel-in-progress: true
    steps:
      - name: Hello! ${{ inputs.username }}
        run: | 
          echo Hello! ${{ inputs.username }}
          sleep 5
