name: Concurrency in Reusable Workflows

on:
  workflow_dispatch:

jobs:
  wait:
    name: Wait
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Wait"
          sleep 5

  concurrency-test1:
    name: Concurrency Test 1
    uses: lucetre/action-concurrency/.github/workflows/reusable-workflow.yaml@main
    with:
      username: lucetre

  concurrency-test2:
    needs: wait
    name: Concurrency Test 2
    uses: lucetre/action-concurrency/.github/workflows/reusable-workflow.yaml@main
    with:
      username: aslan

  concurrency-test3:
    needs: wait
    name: Concurrency Test 3
    uses: lucetre/action-concurrency/.github/workflows/reusable-workflow.yaml@main
    with:
      username: aslan
